#!/usr/bin/env node
/**
 * Builds data/*.json bundles and runtime .data.js files.
 * Run: npm run build:data
 *
 * Source of truth after Phase 1:
 *   data/types/primary.json, data/types/fusions.json
 *   data/maps/*.json
 */
import fs from "fs";
import path from "path";
import vm from "vm";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

const TYPES_BUNDLE = path.join(root, "src/content/hashimonTypes.data.js");
const MAPS_BUNDLE = path.join(root, "src/world/OverworldMaps.data.js");
const WORLD_MAP = path.join(root, "src/world/OverworldMap.js");

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeJson(file, data) {
  ensureDir(path.dirname(file));
  fs.writeFileSync(file, JSON.stringify(data, null, 2) + "\n");
}

function buildTypes() {
  const primaryPath = path.join(root, "data/types/primary.json");
  const fusionsPath = path.join(root, "data/types/fusions.json");

  if (!fs.existsSync(primaryPath) || !fs.existsSync(fusionsPath)) {
    throw new Error("Missing data/types/*.json — run initial extraction first");
  }

  const primary = JSON.parse(fs.readFileSync(primaryPath, "utf8"));
  const fusions = JSON.parse(fs.readFileSync(fusionsPath, "utf8"));
  const primaryKeys = primary.keys;
  const types = primary.types;
  const fusionMap = fusions.fusions;

  const bundle = `// AUTO-GENERATED by tools/build_data.js — edit data/types/*.json then npm run build:data
window.__HASHIMON_TYPES_DATA__ = ${JSON.stringify({ primaryKeys, types, fusionMap })};
`;
  fs.writeFileSync(TYPES_BUNDLE, bundle);
  console.log("types:", primaryKeys.length, "primaries,", Object.keys(fusionMap).length, "fusions");
}

function gridUtils() {
  return {
    withGrid(n) { return n * 16; },
    asGridCoord(x, y) { return `${x * 16},${y * 16}`; },
  };
}

function serializeValue(v) {
  if (v && typeof v === "object" && v.__grid != null) {
    return { __grid: v.__grid };
  }
  if (Array.isArray(v)) {
    return v.map(serializeValue);
  }
  if (v && typeof v === "object") {
    const out = {};
    for (const [k, val] of Object.entries(v)) {
      out[k] = serializeValue(val);
    }
    return out;
  }
  return v;
}

function extractMapsFromOverworldMap() {
  const ctx = vm.createContext({
    window: {},
    utils: gridUtils(),
  });
  ctx.window = ctx;

  const src = fs.readFileSync(WORLD_MAP, "utf8");
  const mapsStart = src.indexOf("window.OverworldMaps = {");
  if (mapsStart === -1) {
    throw new Error("OverworldMaps blob not found — maps should live in data/maps/*.json");
  }
  vm.runInContext(src.slice(mapsStart), ctx);
  return ctx.OverworldMaps;
}

function buildMaps() {
  const mapsDir = path.join(root, "data/maps");
  const indexPath = path.join(mapsDir, "_index.json");
  let rawMaps = {};

  if (fs.existsSync(WORLD_MAP)) {
    const src = fs.readFileSync(WORLD_MAP, "utf8");
    const blobMarker = "window.OverworldMaps = {";
    const mapsStart = src.indexOf(blobMarker);
    if (mapsStart !== -1 && src.indexOf("DemoRoom:", mapsStart) !== -1) {
      const extracted = extractMapsFromOverworldMap();
      ensureDir(mapsDir);
      for (const [id, config] of Object.entries(extracted)) {
        rawMaps[id] = serializeValue(config);
        writeJson(path.join(mapsDir, `${id}.json`), rawMaps[id]);
      }
      writeJson(indexPath, { maps: Object.keys(rawMaps) });
    }
  }

  if (!Object.keys(rawMaps).length && fs.existsSync(indexPath)) {
    const index = JSON.parse(fs.readFileSync(indexPath, "utf8"));
    for (const id of index.maps) {
      rawMaps[id] = JSON.parse(fs.readFileSync(path.join(mapsDir, `${id}.json`), "utf8"));
    }
  }

  if (!Object.keys(rawMaps).length) {
    throw new Error("No map data found — add data/maps/*.json");
  }

  const bundle = `// AUTO-GENERATED by tools/build_data.js — edit data/maps/*.json then npm run build:data
window.__OVERWORLD_MAPS_DATA__ = ${JSON.stringify(rawMaps)};
`;
  fs.writeFileSync(MAPS_BUNDLE, bundle);
  console.log("maps:", Object.keys(rawMaps).length, "files in data/maps/");
}

buildTypes();
buildMaps();
console.log("build:data complete");
