#!/usr/bin/env python3
"""Export Hashimon favicon + wordmark PNGs (pixel art, nearest-neighbor scale)."""
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    raise SystemExit("pip install pillow")

ROOT = Path(__file__).resolve().parent.parent / "images"

# 32x32 favicon: genesis block + creature eyes (crypto palette)
# . = transparent, B = block body, O = outline, E = eye, G = glow, H = highlight
FAVICON_ROWS = """
................................
................................
..........OOOOOOOOOO............
........OOBBBBBBBBBBOO..........
.......OBBBBBBBBBBBBBBO.........
......OBBBBBGGGGGGBBBBBO.......
.....OBBBBBGGEEEEGGBBBBBO......
.....OBBBBGGEE..EEGBBBBBO......
.....OBBBBGGEE..EEGBBBBBO......
.....OBBBBBGGEEEEGGBBBBBO......
.....OBBBBBBGGGGGBBBBBBBO......
.....OBBBBBBBBHHBBBBBBBBO......
.....OBBBBBBBBBBBBBBBBBBO......
.....OBBBBBBBBBBBBBBBBBBO......
......OBBBBBBBBBBBBBBBBO........
.......OBBBBBBBBBBBBBBO.........
........OOBBBBBBBBBBOO..........
..........OOOOOOOOOO............
..........GG....GG..............
.........GGGG..GGGG.............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
""".strip().split("\n")

PALETTE = {
    ".": (0, 0, 0, 0),
    "O": (18, 12, 42, 255),
    "B": (58, 28, 120, 255),
    "G": (0, 229, 255, 255),
    "E": (255, 255, 255, 255),
    "H": (155, 5, 168, 255),
}


def grid_to_image(rows, scale=1):
    h, w = len(rows), len(rows[0])
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    px = img.load()
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            px[x, y] = PALETTE.get(ch, (255, 0, 255, 255))
    if scale > 1:
        img = img.resize((w * scale, h * scale), Image.NEAREST)
    return img


def export_favicon():
    base = grid_to_image(FAVICON_ROWS)
    base.save(ROOT / "favicon.png")
    base.resize((192, 192), Image.NEAREST).save(ROOT / "apple-touch-icon.png")
    base.resize((512, 512), Image.NEAREST).save(ROOT / "hashimon-icon-512.png")


# 128x48 wordmark strip for title screen
LOGO_ROWS = """
................................................................................................
................................................................................................
....OOOO....OOOO....OOOOO...OOOOO....OOOO....OOOO....OOOOO...OOOOO....OOOO....OOOO....OOOOO.....
...O....O..O....O..O.....O.O.....O..O....O..O....O..O.....O.O.....O..O....O..O....O..O.....O...
...O......O......O.O......O.......O......O......O.O......O.O......O......O......O.O......O...
...O......O......O.O......O.......O......O......O.O......O.O......O......O......O.O......O...
...O..OO..O..OO..O.O..OO..O..OO...O..OO..O..OO..O.O..OO..O..OO...O..OO..O..OO..O.O..OO..O..OO..
...O....O..O....O..O....O..O....O..O....O..O....O..O....O..O....O..O....O..O....O..O....O..O....O..
....OOOO....OOOO....OOOOO...OOOOO....OOOO....OOOO....OOOOO...OOOOO....OOOO....OOOO....OOOOO.....
...O......O......O.O......O.......O......O......O.O......O.O......O......O......O.O......O...
...O......O......O.O......O.......O......O......O.O......O.O......O......O......O.O......O...
...O......O......O.O......O.......O......O......O.O......O.O......O......O......O.O......O...
...O......O......O..OOOOO..OOOOO..O......O......O..OOOOO..OOOOO..O......O......O..OOOOO..OOOOO..
................................................................................................
""".strip().split("\n")

LOGO_PALETTE = {
    ".": (0, 0, 0, 0),
    "O": (0, 229, 255, 255),
}


def export_logo_strip():
    img = grid_to_image(LOGO_ROWS, scale=2)
    # tint shadow layer
    w, h = img.size
    out = Image.new("RGBA", (w, h + 8), (0, 0, 0, 0))
    shadow = img.copy()
    shadow_px = shadow.load()
    for y in range(h):
        for x in range(w):
            r, g, b, a = shadow_px[x, y]
            if a:
                shadow_px[x, y] = (18, 12, 42, 180)
    out.paste(shadow, (2, 6))
    out.paste(img, (0, 0))
    out.save(ROOT / "hashimon-wordmark.png")


if __name__ == "__main__":
    ROOT.mkdir(parents=True, exist_ok=True)
    export_favicon()
    print("Wrote favicon.png, apple-touch-icon.png, hashimon-icon-512.png")
